# SPDX-FileCopyrightText: 2006-2024, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Windows MinGW

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: mingw-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: windows-2022
    timeout-minutes: 60
    if: github.repository_owner == 'deNBI-cibi' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Latest"
            build_type: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Export configs
        run: |
          echo "GNUMAKEFLAGS=-j$(getconf _NPROCESSORS_ONLN) --no-print-directory --output-sync=target" >> "${GITHUB_ENV}"
          echo "MAKEFLAGS=-j$(getconf _NPROCESSORS_ONLN) --no-print-directory --output-sync=target" >> "${GITHUB_ENV}"

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake ../ -G "MinGW Makefiles" \
                    -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                    -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror -Wa,-mbig-obj"

      - name: Build tests
        working-directory: build
        run: make -k

      - name: Run tests
        working-directory: build
        run: PATH="/c/mingw64/bin/:${PATH}" ctest . -j --output-on-failure --no-tests=error
