# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Sanitizer

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: sanitizer-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin
  TSAN_OPTIONS: ignore_noninstrumented_modules=1
  UBSAN_OPTIONS: print_stacktrace=1

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    name: ${{ matrix.name }} ${{ matrix.build_type }} ${{ matrix.os }}
    if: github.repository_owner == 'deNBI-cibi' || github.event_name == 'workflow_dispatch'
    env:
      ASAN_OPTIONS: strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:detect_leaks=${{ contains(matrix.os, 'macos') && '0' || '1' }}
    strategy:
      fail-fast: false
      matrix:
        name: [ASan, TSan, UBSan]
        os: [ubuntu-latest, macos-latest]
        build_type: [Release, Debug]
        exclude:
          - name: "TSan"
            os: macos-latest
        include:
          - os: macos-latest
            compiler: clang-latest
          - os: ubuntu-latest
            compiler: gcc-latest
            image: ghcr.io/seqan/gcc-latest

          - name: "ASan"
            os: ubuntu-latest
            cxx_flags: "-fsanitize=address -Wno-maybe-uninitialized"
          - name: "ASan"
            os: macos-latest
            cxx_flags: "-fsanitize=address"

          - name: "TSan"
            os: ubuntu-latest
            compiler: clang-latest
            image: ghcr.io/seqan/clang-latest
            cxx_flags: "-fsanitize=thread"

          - name: "UBSan"
            os: ubuntu-latest
            cxx_flags: "-fsanitize=undefined,float-divide-by-zero"
          - name: "UBSan"
            os: macos-latest
            cxx_flags: "-fsanitize=undefined,float-divide-by-zero,implicit-conversion,local-bounds,nullability"

    container:
      image: ${{ matrix.image || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup compiler
        if: contains(matrix.os, 'macos')
        uses: seqan/actions/setup-compiler@main
        with:
          compiler: ${{ matrix.compiler }}

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                   -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -fno-omit-frame-pointer ${{ matrix.cxx_flags }} -fno-sanitize-recover=all" \
                   -DCMAKE_CXX_STANDARD=26

      - name: Build tests
        working-directory: build
        run: make -k

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure --no-tests=error

