# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Ubuntu 22.04

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ubuntu2204-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc12 (c++17)"
            compiler: "gcc-12"
            build_type: Release
            cxx_flags: "-std=c++17"

          - name: "gcc11 (c++17)"
            compiler: "gcc-11"
            build_type: Release
            cxx_flags: "-std=c++17"

          - name: "gcc10 (c++17)"
            compiler: "gcc-10"
            build_type: Release
            cxx_flags: "-std=c++17"

          - name: "clang14 (c++17)"
            compiler: "clang-14"
            build_type: Release
            cxx_flags: "-std=c++17"

          - name: "gcc12 (c++20)"
            compiler: "gcc-12"
            build_type: Release
            force_std: "-DPROJECT_NAME=tdl -DTDL_ROOT_PROJECT=true"
            cxx_flags: "-std=c++20"

          - name: "gcc11 (c++20)"
            compiler: "gcc-11"
            build_type: Release
            force_std: "-DPROJECT_NAME=tdl -DTDL_ROOT_PROJECT=true"
            cxx_flags: "-std=c++20"

          - name: "gcc10 (c++20)"
            compiler: "gcc-10"
            build_type: Release
            force_std: "-DPROJECT_NAME=tdl -DTDL_ROOT_PROJECT=true"
            cxx_flags: "-std=c++20"

          - name: "gcc12 (c++23)"
            compiler: "gcc-12"
            build_type: Release
            force_std: "-DPROJECT_NAME=tdl -DTDL_ROOT_PROJECT=true"
            cxx_flags: "-std=c++23"

          - name: "gcc12 (c++20, Debug)"
            compiler: "gcc-12"
            build_type: Debug
            force_std: "-DPROJECT_NAME=tdl -DTDL_ROOT_PROJECT=true"
            cxx_flags: "-std=c++20"

    steps:
      - name: Checkout TDL
        uses: actions/checkout@v4
        with:
          path: tdl
          fetch-depth: 2

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 25M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.15.4

      - name: Configure tests
        run: |
          mkdir tdl-build
          cd tdl-build
          cmake ../tdl -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                       -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic ${{ matrix.cxx_flags }} ${{ matrix.force_std }}"

      - name: Build tests
        run: |
          ccache -z
          cd tdl-build
          make -k -j2
          ccache -sv

      - name: Run tests
        run: |
          cd tdl-build
          ctest . -j2 --output-on-failure
