# SPDX-FileCopyrightText: 2006-2024, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Example

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: example-update-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  example-update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.repository_owner == 'deNBI-cibi' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.SEQAN_ACTIONS_PAT }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.SEQAN_ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.SEQAN_ACTIONS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update example
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          commit_author: seqan-actions[bot]
          commit_user_email: seqan-actions@users.noreply.github.com
          commit_message: "[MISC] Update example"
          output_file_paths: '[./README.md,./Example00.cpp.md,./Example01.cpp.md]'
          categories: '[code-block]'
